# Generated by Django 3.2.9 on 2022-02-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20220216_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('skill1', models.CharField(default='', max_length=250)),
                ('skill2', models.CharField(blank=True, default='', max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
